export interface Product {
  id: string;
  name: string;
  category: "living" | "bedroom" | "dining" | "office" | "outdoor";
  itemType: "sofas" | "beds" | "dining" | "chairs" | "tables" | "storage" | "outdoor" | "office";
  categoryLabel: string;
  price: number;
  originalPrice?: number;
  discount?: string;
  rating: number;
  reviews: number;
  material: string;
  materialCategory: "wood" | "fabric" | "leather" | "metal" | "rattan";
  color: "cream" | "grey" | "brown" | "caramel" | "blue" | "black";
  woodType: string;
  dimensions: string;
  inStock: boolean;
  leadTime: string;
  badge?: string;
  image: string;
  gallery: string[];
  description: string;
  features: string[];
}

export const ALL_PRODUCTS: Product[] = [
  {
    id: "haven-sofa",
    name: "Haven Modular Linen Lounge Sofa",
    category: "living",
    itemType: "sofas",
    categoryLabel: "Living Room",
    price: 2450,
    originalPrice: 2890,
    discount: "15% OFF",
    rating: 4.9,
    reviews: 142,
    material: "Belgian Performance Linen",
    materialCategory: "fabric",
    color: "cream",
    woodType: "Solid Chittagong Teak Frame",
    dimensions: "240cm (W) x 105cm (D) x 78cm (H)",
    inStock: true,
    leadTime: "10-14 business days",
    badge: "Best Seller",
    image: "/hero-living-room.jpg",
    gallery: ["/hero-living-room.jpg", "/style-modern.jpg", "/style-scandinavian-3.jpg"],
    description: "A statement of relaxed architectural luxury. The Haven Modular Sofa combines deep feather-blend cushioning with an internal structural frame handcrafted from kiln-dried Chittagong Teak. Designed for deep comfort and lifetime durability.",
    features: [
      "100% Solid Chittagong Teak internal frame with mortise-and-tenon joints",
      "Removable & washable stain-resistant Belgian linen covers",
      "High-resilience foam core wrapped in hypoallergenic duck down",
      "Backed by our 10-Year Structural Frame Warranty",
    ],
  },
  {
    id: "boucle-chair",
    name: "Modern Bouclé & Teak Lounge Chair",
    category: "living",
    itemType: "chairs",
    categoryLabel: "Living Room",
    price: 1250,
    originalPrice: 1550,
    discount: "20% OFF",
    rating: 4.9,
    reviews: 98,
    material: "Textured Cream Bouclé",
    materialCategory: "fabric",
    color: "cream",
    woodType: "Sculpted Solid Teak & Walnut Accents",
    dimensions: "84cm (W) x 88cm (D) x 76cm (H)",
    inStock: true,
    leadTime: "7-10 business days",
    badge: "Deal of Day",
    image: "/lounge-chair.jpg",
    gallery: ["/lounge-chair.jpg", "/style-minimalist.jpg", "/hero-living-room.jpg"],
    description: "Sculptural curves meet warm organic texture. Handcrafted with an ergonomic floating silhouette, solid tapered teak legs, and ultra-plush high-density bouclé upholstery that feels as luxurious as it looks.",
    features: [
      "Hand-shaped solid timber frame with smooth organic radius curves",
      "Heavyweight 450gsm textured bouclé fabric with anti-pilling treatment",
      "Reinforced joint construction supporting up to 250kg static weight",
      "Includes complimentary White-Glove doorstep delivery in Chattogram & Dhaka",
    ],
  },
  {
    id: "verona-dining",
    name: "Verona Live-Edge Solid Teak Dining Table",
    category: "dining",
    itemType: "dining",
    categoryLabel: "Dining",
    price: 2150,
    originalPrice: 2600,
    discount: "18% OFF",
    rating: 5.0,
    reviews: 64,
    material: "Single-Slab Natural Edge Wood",
    materialCategory: "wood",
    color: "brown",
    woodType: "Solid Chittagong Segun (Teak)",
    dimensions: "220cm (L) x 100cm (W) x 76cm (H)",
    inStock: true,
    leadTime: "12-16 business days",
    badge: "Masterpiece",
    image: "/style-classic.jpg",
    gallery: ["/style-classic.jpg", "/style-minimalist.jpg", "/style-scandinavian-3.jpg"],
    description: "A centerpiece created to anchor family gatherings for decades. Each Verona table is cut from seasoned single-plank Chittagong Segun, highlighting natural wood grain, butterfly joints, and an organic live edge.",
    features: [
      "Seasoned for 180 days with kiln-drying to 8% moisture equilibrium",
      "Hand-rubbed organic matte hardwax-oil finish resistant to hot liquids",
      "Solid cast-iron or matching sculpted timber trestle legs",
      "Seats 8-10 people comfortably with generous legroom clearance",
    ],
  },
  {
    id: "aura-bed",
    name: "Aura Minimalist Floating Platform Bed",
    category: "bedroom",
    itemType: "beds",
    categoryLabel: "Bedroom",
    price: 1980,
    originalPrice: 2350,
    discount: "16% OFF",
    rating: 4.9,
    reviews: 82,
    material: "Solid Teak & Italian Upholstered Headboard",
    materialCategory: "wood",
    color: "caramel",
    woodType: "Grade-A Burma & Chittagong Teak",
    dimensions: "King: 183cm (W) x 203cm (L) x 105cm (H)",
    inStock: true,
    leadTime: "10-15 business days",
    badge: "Featured",
    image: "/style-minimalist.jpg",
    gallery: ["/style-minimalist.jpg", "/style-scandinavian-3.jpg", "/hero-living-room.jpg"],
    description: "A tranquil architectural sanctuary. The Aura bed features a recessed cantilever base that gives an illusion of floating weightlessly, complemented by an integrated slatted support system and acoustic padded headboard.",
    features: [
      "Zero-squeak interlocking timber joinery engineered with steel anchor points",
      "Integrated solid wood slatted foundation suitable for all premium mattresses",
      "Customizable headboard available in Italian leather or Belgian linen",
      "Hidden ambient under-glow LED integration ready",
    ],
  },
  {
    id: "fluted-table",
    name: "Fluted Teak Round Pedestal Coffee Table",
    category: "living",
    itemType: "tables",
    categoryLabel: "Living Room",
    price: 790,
    originalPrice: 950,
    discount: "17% OFF",
    rating: 4.8,
    reviews: 73,
    material: "Solid Teak Fluted Tambour",
    materialCategory: "wood",
    color: "caramel",
    woodType: "Solid Seasoned Chittagong Teak",
    dimensions: "90cm (Diameter) x 42cm (H)",
    inStock: true,
    leadTime: "5-7 business days",
    badge: "Popular",
    image: "/style-scandinavian-3.jpg",
    gallery: ["/style-scandinavian-3.jpg", "/style-modern.jpg", "/lounge-chair.jpg"],
    description: "Architectural tambour slats wrap around a cylindrical base, topped with a bevel-edged solid teak surface. A subtle organic centerpiece that balances contemporary lines with artisanal woodwork.",
    features: [
      "Individually hand-milled fluted solid wood tambour perimeter",
      "Water-resistant organic sealant prevents water rings and cup stains",
      "Weighted internal base prevents tipping while keeping mobility easy",
      "Pairable with nested side tables in matching finishes",
    ],
  },
  {
    id: "apex-desk",
    name: "Apex Executive Architectural Desk",
    category: "office",
    itemType: "office",
    categoryLabel: "Office & Study",
    price: 1450,
    originalPrice: 1750,
    discount: "17% OFF",
    rating: 4.9,
    reviews: 47,
    material: "Solid Teak & Italian Saddle Leather",
    materialCategory: "leather",
    color: "black",
    woodType: "Solid Teak & Brass Hardware",
    dimensions: "160cm (W) x 75cm (D) x 76cm (H)",
    inStock: true,
    leadTime: "10-14 business days",
    badge: "Bespoke",
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=1000&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=1000&auto=format&fit=crop", "/style-industrial-brick.jpg", "/style-classic.jpg"],
    description: "Crafted for visionary minds. The Apex Executive Desk pairs solid teak timber with an integrated Italian saddle leather writing pad, discreet soft-close drawers, and magnetic wire concealment channels.",
    features: [
      "Integrated inlaid Italian saddle leather blotter surface",
      "Dovetail solid wood drawers with German soft-close undermount runners",
      "Discreet brushed brass cable grommet and under-desk power tray",
      "Custom drawer divider configurations for documents and tech essentials",
    ],
  },
  {
    id: "chesterfield-sofa",
    name: "Heritage Chesterfield Tufted Leather Sofa",
    category: "living",
    itemType: "sofas",
    categoryLabel: "Living Room",
    price: 2850,
    originalPrice: 3400,
    discount: "16% OFF",
    rating: 5.0,
    reviews: 56,
    material: "Full-Grain Italian Vintage Leather",
    materialCategory: "leather",
    color: "brown",
    woodType: "Solid Teak & Hand-Turned Bun Feet",
    dimensions: "230cm (W) x 98cm (D) x 78cm (H)",
    inStock: true,
    leadTime: "14-18 business days",
    badge: "Collector",
    image: "/style-industrial-brick.jpg",
    gallery: ["/style-industrial-brick.jpg", "/style-classic.jpg", "/style-modern.jpg"],
    description: "The pinnacle of vintage elegance. Hand-tufted with deep diamond buttons across full-grain pull-up leather, anchored by solid teak turned feet with antique brass castors.",
    features: [
      "Individually hand-tied eight-way coil spring suspension system",
      "Top-grade full-grain aniline leather that develops rich patina with age",
      "Deep diamond button tufting applied by seasoned master upholsterers",
      "10-Year Structural Frame Warranty and lifetime craftsmanship guarantee",
    ],
  },
  {
    id: "serenade-credenza",
    name: "Serenade Fluted Solid Teak Media Credenza",
    category: "living",
    itemType: "storage",
    categoryLabel: "Storage & Consoles",
    price: 1650,
    originalPrice: 1980,
    discount: "17% OFF",
    rating: 4.9,
    reviews: 68,
    material: "Solid Teak & Brushed Brass",
    materialCategory: "wood",
    color: "caramel",
    woodType: "Chittagong Teak & Acoustic Mesh",
    dimensions: "200cm (W) x 48cm (D) x 58cm (H)",
    inStock: true,
    leadTime: "10-14 business days",
    badge: "Trending",
    image: "/style-modern.jpg",
    gallery: ["/style-modern.jpg", "/hero-living-room.jpg", "/style-scandinavian-3.jpg"],
    description: "Sculpted fluted door panels glide seamlessly on concealed track hardware. Designed with ventilated acoustic rear ports for sound systems, consoles, and smart media equipment.",
    features: [
      "Precision CNC-milled fluted wave facade with continuous grain flow",
      "Ventilated back panel with organized cable management ports",
      "Adjustable internal solid wood shelving with anti-vibration rubber pins",
      "Push-to-open soft closing mechanisms on all doors",
    ],
  },
  {
    id: "nordic-dresser",
    name: "Nordic 6-Drawer Solid White Oak Dresser",
    category: "bedroom",
    itemType: "storage",
    categoryLabel: "Storage & Wardrobes",
    price: 1390,
    originalPrice: 1650,
    discount: "15% OFF",
    rating: 4.9,
    reviews: 51,
    material: "Solid American White Oak",
    materialCategory: "wood",
    color: "grey",
    woodType: "Kiln-Dried White Oak & Brass Pulls",
    dimensions: "150cm (W) x 50cm (D) x 85cm (H)",
    inStock: true,
    leadTime: "7-10 business days",
    badge: "Heirloom",
    image: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?q=80&w=1000&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1538688525198-9b88f6f53126?q=80&w=1000&auto=format&fit=crop", "/style-scandinavian-3.jpg"],
    description: "Clean geometric lines built with English dovetail joinery. Six deep drawers provide abundant storage for linens and garments with silent soft-close undermount drawer slides.",
    features: [
      "Solid white oak drawer fronts and continuous grain top",
      "English dovetail corner jointing for lifetime longevity",
      "Soft-close hidden undermount runners",
      "Organic matte lacquer finish resisting fingerprints",
    ],
  },
  {
    id: "solstice-dining-chairs",
    name: "Solstice Sculpted Dining Chairs (Set of 2)",
    category: "dining",
    itemType: "chairs",
    categoryLabel: "Dining Seating",
    price: 820,
    originalPrice: 980,
    discount: "16% OFF",
    rating: 4.9,
    reviews: 62,
    material: "Textured Cream Fabric & Teak",
    materialCategory: "fabric",
    color: "cream",
    woodType: "Solid Chittagong Teak",
    dimensions: "54cm (W) x 56cm (D) x 82cm (H)",
    inStock: true,
    leadTime: "5-8 business days",
    badge: "Popular Set",
    image: "https://images.unsplash.com/photo-1580481077197-2a4e21a364bc?q=80&w=1000&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1580481077197-2a4e21a364bc?q=80&w=1000&auto=format&fit=crop", "/style-minimalist.jpg"],
    description: "Curved lumbar support and sculpted teak legs offer unmatched posture support through long dinner parties. Finished with stain-repellent performance upholstery.",
    features: [
      "Sculpted solid teak ergonomic backrest",
      "High-resilience foam cushion with liquid-repellent weave",
      "Floor-protective felt pads pre-installed on all legs",
      "Stackable up to 4 chairs for space-saving storage",
    ],
  },
  {
    id: "riviera-outdoor-lounge",
    name: "Riviera Weatherproof Teak Outdoor Armchair",
    category: "outdoor",
    itemType: "outdoor",
    categoryLabel: "Outdoor & Patio",
    price: 920,
    originalPrice: 1100,
    discount: "16% OFF",
    rating: 4.9,
    reviews: 34,
    material: "Natural Cane Rattan & Teak",
    materialCategory: "rattan",
    color: "caramel",
    woodType: "High-Oil Plantation Teak",
    dimensions: "80cm (W) x 85cm (D) x 75cm (H)",
    inStock: true,
    leadTime: "7-12 business days",
    badge: "Weatherproof",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1000&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1000&auto=format&fit=crop", "/hero-living-room.jpg"],
    description: "Engineered to withstand monsoon humidity and intense sun. Naturally rich in protective teak oils, paired with woven natural cane rattan and fast-draining cushions.",
    features: [
      "Grade-A naturally weather-resistant plantation teak",
      "Handwoven natural cane rattan accents",
      "Stainless steel 316 marine marine hardware",
      "Develops a distinguished silver-grey patina over time outdoors",
    ],
  },
  {
    id: "palisade-dining-table",
    name: "Palisade 6-Seater Tapered Teak Table",
    category: "dining",
    itemType: "tables",
    categoryLabel: "Dining Tables",
    price: 1580,
    originalPrice: 1850,
    discount: "14% OFF",
    rating: 4.8,
    reviews: 44,
    material: "Solid Teak Top & Chamfered Frame",
    materialCategory: "wood",
    color: "brown",
    woodType: "Kiln-Dried Chittagong Teak",
    dimensions: "180cm (L) x 90cm (W) x 76cm (H)",
    inStock: true,
    leadTime: "8-12 business days",
    badge: "Timeless",
    image: "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?q=80&w=1000&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?q=80&w=1000&auto=format&fit=crop", "/style-classic.jpg"],
    description: "Graceful tapered legs support a rounded-edge solid teak tabletop. Perfect proportions for modern apartments and dining rooms seeking timeless warmth.",
    features: [
      "Subtle 45-degree chamfered edge profile",
      "Sturdy corner-braced mortise joinery",
      "Seats 6 comfortably with plenty of tabletop space",
      "Stain-resistant food-safe matte clear finish",
    ],
  },
  {
    id: "zenith-metal-chair",
    name: "Zenith Cast-Iron & Teak Accent Chair",
    category: "living",
    itemType: "chairs",
    categoryLabel: "Accent Seating",
    price: 680,
    originalPrice: 850,
    discount: "20% OFF",
    rating: 4.8,
    reviews: 29,
    material: "Matte Black Steel & Solid Teak",
    materialCategory: "metal",
    color: "blue",
    woodType: "Solid Teak & Powder-Coated Metal",
    dimensions: "62cm (W) x 65cm (D) x 78cm (H)",
    inStock: true,
    leadTime: "5-7 business days",
    badge: "Modernist",
    image: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?q=80&w=1000&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?q=80&w=1000&auto=format&fit=crop", "/style-modern.jpg"],
    description: "Industrial architectural lines softened by warm solid teak armrests and deep slate blue upholstered seat.",
    features: [
      "Architectural powder-coated matte black steel chassis",
      "Hand-rubbed solid teak arm pads",
      "High-density ergonomic seat core",
      "10-Year structural frame guarantee",
    ],
  },
  {
    id: "elysian-canopy-bed",
    name: "Elysian Solid Burma Teak Canopy Bed",
    category: "bedroom",
    itemType: "beds",
    categoryLabel: "Bedroom",
    price: 2650,
    originalPrice: 3100,
    discount: "14% OFF",
    rating: 5.0,
    reviews: 41,
    material: "Solid Burma Teak Post & Beam",
    materialCategory: "wood",
    color: "caramel",
    woodType: "Grade-A 100% Burma Teak",
    dimensions: "King: 190cm (W) x 210cm (L) x 215cm (H)",
    inStock: true,
    leadTime: "14-20 business days",
    badge: "Architectural",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=1000&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=1000&auto=format&fit=crop", "/style-minimalist.jpg"],
    description: "A monument of serenity. The Elysian Canopy Bed features slim architectural posts and mortise-and-tenon corner bracing, bringing dramatic height and peaceful symmetry to your master bedroom.",
    features: [
      "Pure solid Burma Teak four-poster construction",
      "Integrated noise-free interlocking solid timber slats",
      "Hand-sanded satin oil finish highlighting golden honey wood rays",
      "Option for sheer linen canopy drape hanging",
    ],
  },
  {
    id: "solaris-bookcase",
    name: "Solaris Asymmetrical Teak Bookshelf",
    category: "office",
    itemType: "storage",
    categoryLabel: "Storage & Office",
    price: 1120,
    originalPrice: 1350,
    discount: "17% OFF",
    rating: 4.9,
    reviews: 38,
    material: "Solid Chittagong Teak & Brass Pins",
    materialCategory: "wood",
    color: "brown",
    woodType: "Kiln-Dried Chittagong Teak",
    dimensions: "120cm (W) x 38cm (D) x 195cm (H)",
    inStock: true,
    leadTime: "8-12 business days",
    badge: "New Arrival",
    image: "https://images.unsplash.com/photo-1594040226829-7f251ab46d80?q=80&w=1000&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1594040226829-7f251ab46d80?q=80&w=1000&auto=format&fit=crop", "/style-modern.jpg"],
    description: "Playful geometry meets master cabinetry. Open and closed shelving niches create an artful display for collected art, ceramics, and architectural volumes.",
    features: [
      "Staggered open-air display compartments for objects of all heights",
      "Rear anti-tip anchor hardware included",
      "Reinforced timber shelves supporting up to 40kg per tier",
      "Hand-rubbed natural matte wax finish",
    ],
  },
  {
    id: "zen-patio-dining",
    name: "Zen Outdoor Plantation Teak Dining Set",
    category: "outdoor",
    itemType: "outdoor",
    categoryLabel: "Outdoor & Patio",
    price: 1890,
    originalPrice: 2250,
    discount: "16% OFF",
    rating: 4.8,
    reviews: 27,
    material: "Slatted Plantation Teak",
    materialCategory: "wood",
    color: "caramel",
    woodType: "High-Oil Plantation Teak",
    dimensions: "Table: 160cm (L) x 85cm (W) + 4 Chairs",
    inStock: true,
    leadTime: "10-14 business days",
    badge: "Outdoor Set",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop"],
    description: "Complete outdoor dining set engineered with slotted water-drainage gaps and resilient solid teak construction designed for open-air verandas and rooftop terraces.",
    features: [
      "Slatted tops allow rainwater to run off quickly without pooling",
      "Resistant to termites, decay, and tropical humidity",
      "Includes 1 Table + 4 Matching Ergonomic Armchairs",
      "Stainless steel 316 weather-sealed hardware",
    ],
  },
  {
    id: "savoy-modular-sectional",
    name: "Savoy Deep Curved Velvet Sectional",
    category: "living",
    itemType: "sofas",
    categoryLabel: "Living Room",
    price: 2950,
    originalPrice: 3500,
    discount: "15% OFF",
    rating: 4.9,
    reviews: 48,
    material: "Italian Olive Velvet & Teak",
    materialCategory: "fabric",
    color: "grey",
    woodType: "Solid Chittagong Teak Internal Base",
    dimensions: "310cm (W) x 165cm (D) x 76cm (H)",
    inStock: true,
    leadTime: "14-18 business days",
    badge: "Showstopper",
    image: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?q=80&w=1000&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?q=80&w=1000&auto=format&fit=crop", "/hero-living-room.jpg"],
    description: "Architectural sweeping curve with plush feather padding. Designed for luxury entertainment rooms and grand living spaces.",
    features: [
      "Modular 3-piece interlocking sectional layout",
      "Commercial-grade Italian velvet upholstery",
      "Solid teak perimeter under-frame",
      "10-Year structural frame warranty",
    ],
  },
  {
    id: "kyoto-platform-bed",
    name: "Kyoto Low-Profile Japanese Platform Bed",
    category: "bedroom",
    itemType: "beds",
    categoryLabel: "Bedroom",
    price: 1750,
    originalPrice: 2100,
    discount: "16% OFF",
    rating: 4.9,
    reviews: 36,
    material: "Solid Natural Teak & Tatami Slats",
    materialCategory: "wood",
    color: "caramel",
    woodType: "Solid Chittagong Segun",
    dimensions: "Queen: 165cm (W) x 215cm (L) x 40cm (H)",
    inStock: true,
    leadTime: "8-12 business days",
    badge: "Minimalist",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=1000&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=1000&auto=format&fit=crop"],
    description: "Inspired by traditional Japanese joinery. Wide timber ledges double as nightstand surfaces for books and tea.",
    features: [
      "Precision mortise-and-tenon wood locking without metal nails",
      "Integrated solid wood floating side ledges",
      "Natural beeswax matte polish finish",
    ],
  },
  {
    id: "artisan-round-dining",
    name: "Artisan Solid Teak Round Dining Table",
    category: "dining",
    itemType: "dining",
    categoryLabel: "Dining",
    price: 1690,
    originalPrice: 1990,
    discount: "15% OFF",
    rating: 5.0,
    reviews: 52,
    material: "Single-Grain Radial Teak",
    materialCategory: "wood",
    color: "brown",
    woodType: "Kiln-Dried Chittagong Teak",
    dimensions: "135cm (Diameter) x 76cm (H)",
    inStock: true,
    leadTime: "10-14 business days",
    badge: "Intimate Dining",
    image: "https://images.unsplash.com/photo-1617806118233-18e1de247200?q=80&w=1000&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1617806118233-18e1de247200?q=80&w=1000&auto=format&fit=crop"],
    description: "Centering circular table fostering lively conversation. Seats 4-6 comfortably around a sculpted central pedestal.",
    features: [
      "Solid 40mm thick beveled tabletop",
      "Zero leg interference with geometric center pedestal",
      "Heat and spill-resistant organic seal",
    ],
  },
  {
    id: "oslo-leather-armchair",
    name: "Oslo Mid-Century Caramel Leather Armchair",
    category: "living",
    itemType: "chairs",
    categoryLabel: "Accent Seating",
    price: 1150,
    originalPrice: 1390,
    discount: "17% OFF",
    rating: 4.8,
    reviews: 43,
    material: "Aniline Top-Grain Leather & Teak",
    materialCategory: "leather",
    color: "brown",
    woodType: "Sculpted Solid Teak",
    dimensions: "78cm (W) x 82cm (D) x 80cm (H)",
    inStock: true,
    leadTime: "6-9 business days",
    badge: "Classic",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1000&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1000&auto=format&fit=crop"],
    description: "Architectural angled arms hand-turned from solid timber with glove-soft caramel leather cushioning.",
    features: [
      "Top-grain pull-up leather that grows more beautiful with age",
      "Feather and high-density foam combination cushion",
      "Mortise jointed solid teak chassis",
    ],
  },
  {
    id: "travertine-coffee-table",
    name: "Travertine & Teak Monolith Coffee Table",
    category: "living",
    itemType: "tables",
    categoryLabel: "Living Room",
    price: 890,
    originalPrice: 1050,
    discount: "15% OFF",
    rating: 4.9,
    reviews: 31,
    material: "Roman Travertine Stone & Solid Teak",
    materialCategory: "wood",
    color: "cream",
    woodType: "Solid Teak Frame & Natural Stone Top",
    dimensions: "110cm (L) x 65cm (W) x 40cm (H)",
    inStock: true,
    leadTime: "7-10 business days",
    badge: "Editorial",
    image: "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?q=80&w=1000&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?q=80&w=1000&auto=format&fit=crop"],
    description: "Unfilled natural Roman travertine honed stone slab resting securely on a sculpted solid teak architectural base.",
    features: [
      "Natural unfilled honed travertine stone top",
      "Stain-sealed stone surface",
      "Interlocking solid teak foundation",
    ],
  },
  {
    id: "monolith-sideboard",
    name: "Monolith 4-Door Fluted Teak Sideboard",
    category: "dining",
    itemType: "storage",
    categoryLabel: "Dining & Storage",
    price: 1850,
    originalPrice: 2200,
    discount: "16% OFF",
    rating: 4.9,
    reviews: 28,
    material: "Solid Teak & Antique Brass Legs",
    materialCategory: "wood",
    color: "caramel",
    woodType: "Solid Chittagong Teak",
    dimensions: "190cm (W) x 45cm (D) x 80cm (H)",
    inStock: true,
    leadTime: "12-16 business days",
    badge: "Statement Piece",
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?q=80&w=1000&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1595428774223-ef52624120d2?q=80&w=1000&auto=format&fit=crop"],
    description: "Generous dining buffet and bar storage with 4 push-to-open soft closing doors and adjustable timber shelves.",
    features: [
      "Hand-fluted solid teak facade",
      "Four discrete soft-close doors with hidden German hinges",
      "Cable management access ports for dining entertainment use",
    ],
  },
  {
    id: "hamptons-chaise-lounge",
    name: "Hamptons Reclining Teak Sun Lounger",
    category: "outdoor",
    itemType: "outdoor",
    categoryLabel: "Outdoor & Pool",
    price: 1050,
    originalPrice: 1250,
    discount: "16% OFF",
    rating: 4.8,
    reviews: 22,
    material: "Grade-A Plantation Teak & QuickDry Foam",
    materialCategory: "wood",
    color: "caramel",
    woodType: "High-Oil Plantation Teak",
    dimensions: "200cm (L) x 68cm (W) x 35cm (H)",
    inStock: true,
    leadTime: "8-12 business days",
    badge: "Outdoor Luxury",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1000&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1000&auto=format&fit=crop"],
    description: "5-position reclining sun lounger with concealed rubber-tread wheels for smooth mobility around poolside decks.",
    features: [
      "5-position ratchet backrest adjustment",
      "Integrated slide-out drinks tray table",
      "Sunbrella weather-sealed cushion included",
    ],
  },
  {
    id: "architect-standing-desk",
    name: "Architect Solid Oak Motorized Standing Desk",
    category: "office",
    itemType: "office",
    categoryLabel: "Office & Study",
    price: 1720,
    originalPrice: 2050,
    discount: "16% OFF",
    rating: 5.0,
    reviews: 45,
    material: "Solid American Oak & Dual-Motor Steel",
    materialCategory: "metal",
    color: "black",
    woodType: "Solid 35mm American White Oak Slab",
    dimensions: "160cm (W) x 80cm (D) x 65-130cm (H)",
    inStock: true,
    leadTime: "7-10 business days",
    badge: "Ergonomic Pro",
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=1000&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=1000&auto=format&fit=crop"],
    description: "Solid hardwood warmth meets whisper-quiet height adjustability. Programmable memory presets with anti-collision safety.",
    features: [
      "Continuous solid white oak slab with beveled front edge",
      "Dual German electric motors with 4 digital height presets",
      "Integrated steel under-desk power and wire trough",
    ],
  },
];
